### ISSUE TITLE
404 Not Found error

### ISSUE THREAD

**Issue by Aneith** [faceterteam/FaceterFOGClient#10]
Hello,

For a couple of months now, when I launch the Faceter demo webclient (http://localhost/#/ , I have the following error msg: 404 Not Found | nginx/1.15.6

I followed the instructions and reinstalled faceter client with no success? Any idea what is going on?

Need your advice before reinstalling eventually nginx.

Thanks.

**Comment by faceterio** [comment]
Hello Aneith 
Thank you for your feedback. 
For now, we had excluded demo part of Faceter Fog Client from the product. You able to create some contract between camera owner and miner and found recognition results in the main faceter cabinet on the https://cloud.faceter.cam/public/signin/

**Comment by Aneith** [comment]
Got it. Thank you for your answer
