### ISSUE TITLE
3 Faceterfogclient containers not working properly

### ISSUE THREAD

**Issue by Aneith** [faceterteam/FaceterFOGClient#20]
Hello,

For the past few months, I have been experiencing 3 containers being either unhealthy (faceterfog_client_recognition-webapi and faceterfogclient_recognition-project-manager-worker_1) and stopped (faceterfogclient_mongo_1).

This does not prevent me to be active as a fog miner and visible for a Fog camera owner client. So I was wondering whether this is normal ?!?!

FYI - I reinstalled the fogagent as well as docker, nvidia docker etc a couple of time from scratch.

Let me know if you need the log files of the faulty containers.

Thanks.

![faceterfogclient containers status](https://user-images.githubusercontent.com/59732543/96571778-52665a80-12cc-11eb-809a-a6d52255adc4.png)

**Comment by faceterio** [comment]
Hello,

Can you provide a docker logs for that containers?

As well that prevent to execute a task of contract.

**Comment by Aneith** [comment]
Please find enclosed the log files for the faulty/stopped containers.

[faceterfogclient_faulty-stopped_containers.zip](https://github.com/faceterteam/FaceterFOGClient/files/5421979/faceterfogclient_faulty-stopped_containers.zip)

**Comment by faceterio** [comment]
> Please find enclosed the log files for the faulty/stopped containers.
> 
> [faceterfogclient_faulty-stopped_containers.zip](https://github.com/faceterteam/FaceterFOGClient/files/5421979/faceterfogclient_faulty-stopped_containers.zip)

ok, it seems MongoDB container problem at all. Can you try to make `docker restart faceterfogclient_mongo_1` and collect the container's logs again?

**Comment by Aneith** [comment]
Here it is attached. I did a restart of mongo container.

[faceterfogclient_mongo_1-json.log.zip](https://github.com/faceterteam/FaceterFOGClient/files/5423278/faceterfogclient_mongo_1-json.log.zip)

**Comment by Aneith** [comment]
Hello, any update from your investigation on the log of the mongo_1 container?

**Comment by faceterio** [comment]
Something goes wrong with MongoDB, can you try to docker stop mongo_1, docker system prune then restart?

**Comment by Aneith** [comment]
Just did what you recommended. Mongo_1 is still stopped.

**Comment by faceterio** [comment]
same logs?

**Comment by faceterio** [comment]
docker system prune should delete stopped containers, after restart fog_agent it will be download a new image of MongoDB

**Comment by Aneith** [comment]
I reinstalled all images and rebuilt all containers from scratch. Still mongo_1 is stopped.

What is interesting is that fogagent keeps recreating containers and images but face a coredump (see below)

Oct 30 11:59:26 grandpas fogagent[16772]: Nvidia driver with CUDA version 10.0 or later installed!
Oct 30 11:59:26 grandpas fogagent[16772]: Docker version 18.06.0 or later installed and running!
Oct 30 11:59:26 grandpas fogagent[16772]: Checking containers...
Oct 30 11:59:26 grandpas fogagent[16772]: Containers checked
Oct 30 11:59:26 grandpas fogagent[16772]: Found containers with non-active state: faceterfogclient_mongo_1 - exited
Oct 30 11:59:26 grandpas fogagent[16772]: Recreating containers and networks and updating images...
Oct 30 11:59:26 grandpas fogagent[16772]: Pulling images...
#:/etc/fogagent$ sudo systemctl status fogagent
● fogagent.service - Faceter Fog Client
     Loaded: loaded (/etc/systemd/system/fogagent.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Fri 2020-10-30 11:59:41 CET; 474ms ago
    Process: 16772 ExecStart=/usr/bin/fogagent (code=dumped, signal=ABRT)
   Main PID: 16772 (code=dumped, signal=ABRT)
#:/etc/fogagent$

Attached the logfile again for mongo_1
[faceterfogclient_mongo_1-json.log](https://github.com/faceterteam/FaceterFOGClient/files/5464725/faceterfogclient_mongo_1-json.log)

**Comment by Aneith** [comment]
#:~$ sudo systemctl status fogagent
● fogagent.service - Faceter Fog Client
     Loaded: loaded (/etc/systemd/system/fogagent.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-10-30 13:52:44 CET; 8min ago
   Main PID: 41929 (fogagent)
      Tasks: 13 (limit: 38153)
     Memory: 54.1M
     CGroup: /system.slice/fogagent.service
             └─41929 /usr/bin/fogagent

Oct 30 13:59:07 grandpas fogagent[41929]: Delaying for 00:00:04.0810000 before 2-th retry request because 'StatusCode: InternalServerError'
Oct 30 13:59:15 grandpas fogagent[41929]: Recognition tasks are being synchronized with Fog...
Oct 30 13:59:41 grandpas fogagent[41929]: Delaying for 00:00:08.0420000 before 3-th retry request because 'StatusCode: InternalServerError'
Oct 30 13:59:45 grandpas fogagent[41929]: Recognition task statistics sent failed: A task was canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action>
Oct 30 13:59:50 grandpas fogagent[41929]: Delaying for 00:00:02.0830000 before 1-th retry request because 'StatusCode: InternalServerError'
Oct 30 14:00:22 grandpas fogagent[41929]: Delaying for 00:00:04.0420000 before 2-th retry request because 'StatusCode: InternalServerError'
Oct 30 14:00:45 grandpas fogagent[41929]: Recognition task statistics are being sent to Fog...
Oct 30 14:00:56 grandpas fogagent[41929]: Delaying for 00:00:08.0510000 before 3-th retry request because 'StatusCode: InternalServerError'
Oct 30 14:01:00 grandpas fogagent[41929]: Recognition tasks synchronize failed: A task was canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, C>
Oct 30 14:01:15 grandpas fogagent[41929]: Delaying for 00:00:02.0210000 before 1-th retry request because 'StatusCode: InternalServerError'

**Comment by faceterio** [comment]
StatusCode - InternalServerError, Thats because of mongoDB unavailable. In the mongo container's logs there are
"the process must exit and restart: WT_PANIC: WiredTiger library panic\n"

**Comment by Aneith** [comment]
Hi, any update? Does the fact that mongo container is down prevent me to a miner?

**Comment by faceterio** [comment]
We can recommend to prune all containers and reinstall Fog agent, we have no way to fix Mongo's error in this case.

**Comment by Aneith** [comment]
I just did a full reinstall of docker-ce, latest nvidia drivers, all faceter images and faceter ocntainers. Even the fogagent is the latest one ... still have the same issue with mongo db. I don't know what to do anymore. I also saw that someone tried to create a contract this afternoon and cancel it right after.

Hope this doe snot affect my ability to be a miner otherwise I would appreciate your help. I have been one of the first beta testers of faceter hence I would hate not to be able to be a miner.

Thanks in advance for your assistance.

**Comment by faceterio** [comment]
Sure, can you attach latest logs from docker containers?

**Comment by faceterio** [comment]
also we need system environments, such as OS type, version, CPU/RAM/GPU

**Comment by Aneith** [comment]
Hello! Here is all the information hopefully you need.
FYI - since the latest fogagent upgrade then another container is stopped in addition of mongo: faceterfogclient_recognition-person-storage_1

**Comment by Aneith** [comment]
Hello! ok. So I restored a very old image of my operating system, and decided to reinstall fogagent from scratch. Finally it works. All images were downloaded, network created, and containers built. I also requested a new secret key, and I have now 12 containers running, including 2 healthy containers.
Thanks for your help.
