### ISSUE TITLE
Contracts failed

### ISSUE THREAD

**Issue by Aneith** [faceterteam/FaceterFOGClient#8]
Dear Faceter team, - as a miner I wanted to let you know about 3 failed attempts to get a contract this morning. Not sure whether it is coming from you or end-users? I wanted to let you know about this because the initial contract from Jan 4th worked.
Let me know what kind of information you need if needed. Thanks.

**Comment by faceterio** [comment]
Thats happened because of camera's owner balance insufficient.
best regards

**Comment by Aneith** [comment]
Thank you for your answer. Appreciated.


Best regards.

Le 17 janvier 2020 à 13:21, faceterio <notifications@github.com> a écrit :



Thats happened because of camera's owner balance insufficient.
best regards
